// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/api/auth/check-role": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/services": {
    params: {};
  };
  "/logs": {
    params: {};
  };
  "/metrics": {
    params: {};
  };
  "/ci-cd": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.js": {
    id: "root";
    page: "/" | "/auth" | "/api/auth/check-role" | "/api/auth/*" | "/services" | "/logs" | "/metrics" | "/ci-cd" | "/docs" | "/docs/:slug";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/api.auth.check-role.tsx": {
    id: "routes/api.auth.check-role";
    page: "/api/auth/check-role";
  };
  "routes/api.auth.$.tsx": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/logs.tsx": {
    id: "routes/logs";
    page: "/logs";
  };
  "routes/metrics.tsx": {
    id: "routes/metrics";
    page: "/metrics";
  };
  "routes/ci-cd.tsx": {
    id: "routes/ci-cd";
    page: "/ci-cd";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
  "routes/docs.$slug.tsx": {
    id: "routes/docs.$slug";
    page: "/docs/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.js");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
  "routes/api.auth.check-role": typeof import("./app/routes/api.auth.check-role.tsx");
  "routes/api.auth.$": typeof import("./app/routes/api.auth.$.tsx");
  "routes/services": typeof import("./app/routes/services.tsx");
  "routes/logs": typeof import("./app/routes/logs.tsx");
  "routes/metrics": typeof import("./app/routes/metrics.tsx");
  "routes/ci-cd": typeof import("./app/routes/ci-cd.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/docs.$slug": typeof import("./app/routes/docs.$slug.tsx");
};